### ISSUE TITLE
When I use your library, this message app here "there is no product"

### ISSUE THREAD

**Issue by sam9010** [contoriel/react-native-cafe-bazaar#12] opened 2019-01-21 05:53 UTC
hi
I used your library to pay for the app
And I did all the settings that you said, But my app encountered an error
When I use this message" there is no product"
my code:
````
   CafeBazaar.open()
            .then(() => CafeBazaar.purchase('tansazReactNative', '', 1840))
            .then((details) => {
                alert(JSON.stringify(details));
                return CafeBazaar.close()
            })
            .catch((err) =>{
                if(err.code==="E_SETUP_DISCONNECT"){
                    alert("cafeBazaar Not install, please install it and so try again");
                }else{
                    alert(JSON.stringify(err))
                }
            } );
````

You can see for better
[picture of mycode+result in my app](https://ibb.co/tQR1dLQ)

thanks

**Comment by arashmilani** [comment] 2019-01-21 13:53
Thank you for submitting the issue. What is the `err.code` for this specific error you are getting?

**Comment by sam9010** [comment] 2019-01-22 05:56
Yes it is there

 [you can see it](https://ibb.co/TbDWPJT)

**Comment by sam9010** [comment] 2019-01-22 07:15
I found my problem
The package project should be the name of the package in the cafe bazaar
:)

I tested the sample project

**Comment by arashmilani** [comment] 2019-01-22 08:01
آappy to hear that you found the cause of the issue. So I'm closing this issue.

**Closed by arashmilani** 2019-01-22 08:01 UTC
